# CMake generated Testfile for 
# Source directory: /home/ben/dev/openapv
# Build directory: /home/ben/dev/openapv/build_check
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Encoder_runs "/home/ben/dev/openapv/build_check/bin/oapv_app_enc")
set_tests_properties(Encoder_runs PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;258;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(Decoder_runs "/home/ben/dev/openapv/build_check/bin/oapv_app_dec")
set_tests_properties(Decoder_runs PROPERTIES  _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;261;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(encode "/home/ben/dev/openapv/build_check/bin/oapv_app_enc" "-i" "/home/ben/dev/openapv/test/sequence/pattern1_yuv422p10le_320x240_25fps.y4m" "-w" "320" "-h" "240" "-z" "25" "-o" "out.oapv")
set_tests_properties(encode PROPERTIES  FAIL_REGULAR_EXPRESSION "Encoded frame count               = 0" PASS_REGULAR_EXPRESSION "Encoded frame count               = 125" RUN_SERIAL "TRUE" TIMEOUT "20" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;264;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "out.oapv")
set_tests_properties(decode PROPERTIES  DEPENDS "encode" FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION "Decoded frame count               = 125" RUN_SERIAL "TRUE" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;273;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_qp_A "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/qp_A.apv" "-v" "3" "--hash")
set_tests_properties(decode_qp_A PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;283;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_qp_B "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/qp_B.apv" "-v" "3" "--hash")
set_tests_properties(decode_qp_B PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;292;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_qp_C "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/qp_C.apv" "-v" "3" "--hash")
set_tests_properties(decode_qp_C PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;301;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_qp_D "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/qp_D.apv" "-v" "3" "--hash")
set_tests_properties(decode_qp_D PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;310;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_qp_E "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/qp_E.apv" "-v" "3" "--hash")
set_tests_properties(decode_qp_E PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;319;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_syn_A "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/syn_A.apv" "-v" "3" "--hash")
set_tests_properties(decode_syn_A PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;328;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_syn_B "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/syn_B.apv" "-v" "3" "--hash")
set_tests_properties(decode_syn_B PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;337;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_tile_A "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/tile_A.apv" "-v" "3" "--hash")
set_tests_properties(decode_tile_A PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;346;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_tile_B "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/tile_B.apv" "-v" "3" "--hash")
set_tests_properties(decode_tile_B PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;355;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_tile_C "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/tile_C.apv" "-v" "3" "--hash")
set_tests_properties(decode_tile_C PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;364;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_tile_D "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/tile_D.apv" "-v" "3" "--hash")
set_tests_properties(decode_tile_D PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;373;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
add_test(decode_tile_E "/home/ben/dev/openapv/build_check/bin/oapv_app_dec" "-i" "/home/ben/dev/openapv/test/bitstream/tile_E.apv" "-v" "3" "--hash")
set_tests_properties(decode_tile_E PROPERTIES  FAIL_REGULAR_EXPRESSION "Decoded frame count               = 0" PASS_REGULAR_EXPRESSION ".*hash:match.*" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/ben/dev/openapv/CMakeLists.txt;382;add_test;/home/ben/dev/openapv/CMakeLists.txt;0;")
subdirs("src")
subdirs("app")
